version: '3.7'

networks:
  traefik-public:
    external: true
    
services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    networks:
      - traefik-public
    security_opt:
      - no-new-privileges:true
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    environment:
      - TZ=America/Maceio
    labels:
      - traefik.enable=true
      - traefik.network=traefik-public
      - traefik.http.routers.portainer-rtr.entrypoints=websecure
      - traefik.http.routers.portainer-rtr.rule=Host(`portainer.guilhermebraz.tech`)
      - traefik.http.routers.portainer-rtr.tls=true
      - traefik.http.routers.portainer-rtr.tls.certresolver=letsencrypt
      - traefik.http.services.portainer-svc.loadbalancer.server.port=9000

  traefik:
    container_name: traefik
    image: traefik:latest
    ports:
      - 80:80
      - 443:443

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.traefik-rtr.entrypoints=websecure
      - traefik.http.routers.traefik-rtr.rule=Host(`traefik.guilhermebraz.tech`)
      - traefik.http.routers.traefik-rtr.service=api@internal
      - traefik.http.routers.traefik-rtr.tls=true
      - traefik.http.routers.traefik-rtr.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-rtr.tls.domains[0].main=guilhermebraz.tech
      # Enable HTTP Basic auth, using the middleware created above
      # - traefik.http.routers.traefik-rtr.middlewares=basic-auth@file
      # Define the port inside of the Docker service to use
      - traefik.http.services.traefik-svc.loadbalancer.server.port=8080
    volumes:
      - ./traefik/rules:/rules
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/letsencrypt:/letsencrypt
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=guilhermebraz089@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      # Uso de Let's Encrypt staging server para testes
      # - --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --accesslog
      - --log
      - --api
    networks:
      - traefik-public
