## Dynamic configuration

##Redirect all http to https
[http.routers]
  [http.routers.redirect-to-https-rtr]
    entryPoints = ["web"]
    rule = "HostRegexp(`{host:.+}`)"
    priority = 1
    middlewares = "redirect-to-https@file"
    service = "noop@internal"


##MIDDLEWARES
[http.middlewares]

##autenticação basica
  [http.middlewares.basic-auth]
    [http.middlewares.basic-auth.basicAuth]
      users = [
        "admin:$2y$05$GWP7NHlYo9jK/YPkf.oCd.5WrxliYosVTLr4AKexMr0i1ERfJiXcm",
      ]

## Redirect to https
  [http.middlewares.redirect-to-https]
    [http.middlewares.redirect-to-https.redirectScheme]
      scheme = "https"
      permanent = true